# Generated by Django 2.1.4 on 2020-05-22 07:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created')),
                ('modified', models.DateTimeField(default=django.utils.timezone.now, verbose_name='modified')),
                ('typetree', models.TextField(blank=True)),
            ],
        ),
    ]
