# Generated by Django 2.1.4 on 2020-05-23 09:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ns', '0002_usertypes'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeSchema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created')),
                ('modified', models.DateTimeField(default=django.utils.timezone.now, verbose_name='modified')),
                ('version', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('title', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('data_str', models.TextField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='UserTypes',
        ),
        migrations.RenameField(
            model_name='graphsession',
            old_name='graphdef',
            new_name='data_str',
        ),
        migrations.AddField(
            model_name='graphsession',
            name='org_version',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
